apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world-workflow
  namespace: test38
spec:
  serviceAccountName: run-workflow  # Specify the ServiceAccount
  entrypoint: pull-source
  volumes:
  - name: workdir
    emptyDir: {}
  - name: cacert
    configMap:
      name: enterprise-ca
  - name: github-app-key
    secret:
      secretName: app-key
  - name: github-infra-key
    secret:
      secretName: cicd-key
  - name: harbor-secret
    secret:
      secretName: cicd-secret
  templates:
    - name: pull-source
      container:
        image: alpine/git
        command: ['sh','-c']
        args: 
        - |
            mkdir -p ~/.ssh
            cp /mnt/github-app/id_rsa ~/.ssh/id_rsa
            echo "StrictHostKeyChecking no" >> ~/.ssh/config
            chmod -R 600 ~/.ssh
            cd /workdir
            git clone git@github.com:ts-idp-poc/test38-app.git
            cd workdir/test38-app
            LATEST_COMMIT=$(git rev-parse --short HEAD)
            echo -n $LATEST_COMMIT > /workdir/tag.txt
            cat /workdir/tag.txt
        volumeMounts:
        - name: workdir
          mountPath: /workdir
        - name: github-app-key
          mountPath: /mnt/github-app

    
        

    
    
    # - name: pull-source
    #   script:
    #     image: gcr.io/kaniko-project/executor:v1.14.0-debug
    #     command: ['sh']
    #     script: |
    #       mkdir -p /kaniko/.docker
    #       cp /mnt/harbor/.dockerconfiguration /kaniko/.docker/config.json
    #       /kaniko/executor \
    #         --dockerfile